Fix minesweeper rep earned message
Bluesy1/CharB0T pull request #218
Opened 2022-10-03 21:09 UTC by jwill0213

Fix issue with passing context with data into translator translate function.

Add test file for translator.

2022-10-03 21:51 UTC, Bluesy1 requested changes
One small typing nitpick, otherwise LGTM!

2022-10-03 21:51 UTC, Bluesy1 commented on tests/charbot/test_translator.py
> +    assert "You gained 5 points." in result, "Should say awarded 5 points"
```suggestion
    assert result is not None, "Result should not be None"
    assert "You gained 5 points." in result, "Should say awarded 5 points"
```

2022-10-04 04:10 UTC, jwill0213 commented
Removed match case for translator.py. Pyright was being very picky with the types and just made a mess to use. Would have made the code a lot less readable.

2022-10-04 05:05 UTC, Bluesy1 commented
Hopefully pyright behaves ... I'll figure out a solution eventually to use match-case

2022-10-04 05:15 UTC, merged