refactored into a package
Bluesy1/CharB0T pull request #248
Opened 2022-10-22 18:42 UTC by ShivamGarg2910

## Checklist
- [ Y] I have read the [contributing guidelines](./CONTRIBUTING.md).
- [ Y] The changes are for an issue, or have been discussed with Bluesy.
- [ ] I have checked the code for syntax errors or non conforming style and fixed them to the best of my ability.

###  Changes

refactoring giveaway.py into a package.

Closes: 237

### Pending items
- Python version not mentioned. @Bluesy1: pleas share python version, getting syntax errors.
- Testcases pending, waiting for python version

2022-10-22 19:06 UTC, Bluesy1 commented
@ShivamGarg2910 I target python3.10

2022-10-22 19:12 UTC, Bluesy1 requested changes
the setup function should be in `__init__.py`, not `cog.py`, like here: https://github.com/Bluesy1/CharB0T/blob/890c5d1515987bd8e051ff538b8cf140ea9e81a9/charbot/programs/__init__.py#L16-L23

Besides that and test coverage, LGTM!

2022-10-25 15:08 UTC, Bluesy1 requested changes
See comments + please rebase off of main.

2022-10-25 15:08 UTC, Bluesy1 commented on charbot/giveaway/view.py
>  # -*- coding: utf-8 -*-
Need to run black on this file.

2022-10-25 15:08 UTC, Bluesy1 commented on charbot/giveaway/cog.py
> +# -*- coding: utf-8 -*-
Need to run black on this file

2022-10-28 17:27 UTC, Bluesy1 commented
@ShivamGarg2910 i'd like to push this through in the next week or so, preferably before hacktoberfest ends too.

Any update?

2022-10-30 07:18 UTC, ShivamGarg2910 commented
Hey @Bluesy1, have been a little under the weather, will try finishing it up asap.

2022-10-30 14:22 UTC, Bluesy1 commented
@ShivamGarg2910 ah no worries, feel better soon

2022-10-30 18:15 UTC, ShivamGarg2910 commented
Hey @Bluesy1, please help by confirming that pending tasks are running the black commands and moving setup function to __init__.py

2022-10-30 18:27 UTC, ShivamGarg2910 commented on charbot/giveaway/view.py
>  # -*- coding: utf-8 -*-
resolved

2022-10-30 19:08 UTC, Bluesy1 submitted a review, later dismissed
LGTM! @ShivamGarg2910 please just resolve the merge conflict (or let me know if you want me to, i'm happy to do it because its a complex one)

2022-10-30 19:18 UTC, ShivamGarg2910 commented
@Bluesy1, can you please resolve the merge conflict, and share some guide on how to do the same.
Coz I tried the rebase and merge, but no conflicts came.

2022-10-30 20:03 UTC, Bluesy1 commented
@ShivamGarg2910 i've taken care of the merge/rebase
Unfortunately i don't have a great guide to show you besides [github's docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github), but what i did here was i clone your fork into my IDE (integrated development environment), in py case PyCharm, which is free for students via teh Github Education Pack, and told it to checkout and rebase your branch onto main (in hindsight, a merge should have been done over a rebase, apologies for that). 
Git clients can help with this, like Github Desktop, GitKraken, even the one in VSCode
Once CI passes, this is now ready to merge, thanks for your contributon!

2022-10-30 20:04 UTC, Bluesy1 approved these changes
LGTM! Waiting for CI to pass

2022-10-30 20:09 UTC, Bluesy1 commented on charbot/giveaway/cog.py
> +from . import GiveawayView
```suggestion
if TYPE_CHECKING:
    from . import GiveawayView
```

2022-10-30 20:09 UTC, Bluesy1 commented on charbot/giveaway/cog.py
> +"""Giveaway  commands."""
```suggestion
"""Giveaway  commands."""
from __future__ import annotations
```

2022-10-30 20:09 UTC, Bluesy1 commented on charbot/giveaway/cog.py
> +from typing import cast
```suggestion
from typing import TYPE_CHECKING, cast
```

2022-10-30 20:10 UTC, Bluesy1 commented on charbot/giveaway/cog.py
> +
```suggestion
```

2022-10-30 20:11 UTC, merged

2022-10-30 20:11 UTC, Bluesy1 commented
Thanks for your contribution!